apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  pod.cnf: |
    [mysqld]
    #Bin logs
    log_bin=/opt/mysql/data/mysql-bin
    relay_log=/opt/mysql/data/mysql-relay-bin
    log_slave_updates=true

    #Encryption
    plugin_load_add = file_key_management
    file_key_management_filename = /etc/mysql/conf.d/.keys
    file_key_management_encryption_algorithm = aes_ctr
    encrypt-tmp-disk-tables = 0
    encrypt-tmp-files = 0
    encrypt_binlog = ON

    innodb_default_encryption_key_id = 1
    innodb_encrypt_tables = ON
    innodb_encrypt_log = OFF
    innodb_encryption_threads = 4

    #Some tweaks
    innodb_flush_method = O_DIRECT
    innodb_buffer_pool_size = 1G
    innodb_flush_log_at_trx_commit=1
    innodb_log_file_size = 256M
    innodb_thread_concurrency = 0

