apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  pod.cnf: |
    # Apply this config only on the master.
    [mysqld]
    log_bin=/opt/mysql/data/mysql-bin
    relay_log=/opt/mysql/data/mysql-relay-bin
    log_slave_updates=true
    plugin_load_add = file_key_management
    file_key_management_filename = /etc/mysql/conf.d/.keys
    file_key_management_encryption_algorithm = aes_ctr

    innodb_default_encryption_key_id = 1
    innodb_encrypt_tables = ON
    innodb_encrypt_log = OFF
    innodb_encryption_threads = 4

    encrypt-tmp-disk-tables = 0
    encrypt-tmp-files = 0
    encrypt_binlog = ON
