apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  root_password: cGFzc3dvcmQ=
  slave_password: cGFzc3dvcmQ=
  db_username: dXNlcg==
  db_password: cGFzc3dvcmQ=
  backup_password: cGFzc3dvcmQ=
  encryption_key: 1c4bed6afe83aeb2d8604bbda7c29400
