# Headless service for stable DNS entries of StatefulSet members.
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  externalTrafficPolicy: Local
  ports:
  - nodePort: 30090
    targetPort: 3306
    port: 30090
    protocol: TCP
    #- name: mysql
    #port: 3306
  #clusterIP: None
  type: NodePort
  selector:
    app: mysql
