kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-backup-pvc
spec:
  storageClassName: mysql-backup-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

